os: osx
osx_image: xcode10.2
language: swift
env:
  - 'INTEGRATION=1'
install:
  - 'brew update'
  - 'brew install python@2'
  - 'brew install pipenv'
  - 'pipenv install --dev'
script:
  - 'pipenv run pytest'
  - 'pipenv run flake8'