# BUILD FILE SYNTAX: SKYLARK

#  Copyright (c) 2021 Uber Technologies, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This code was @generated by Uber Poet, a mock application generator.
# Check it out at https://github.com/uber/uber-poet

load("@build_bazel_rules_apple//apple:ios.bzl", "ios_unit_test")
load("@build_bazel_rules_swift//swift:swift.bzl", "swift_library")

swift_library(
    name = "{0}",
    module_name = "{0}",
    srcs = glob([
        "Sources/**/*.swift",
    ]),
    visibility = ["//visibility:public"],
    deps = [
        {1}
    ],
)

swift_library(
    name = "{0}TestsLib",
    module_name = "{0}TestsLib",
    srcs = glob([
        "Tests/**/*.swift",
    ]),
    deps = [":{0}"],
)

ios_unit_test(
    name = "{0}Tests",
    minimum_os_version = "12.0",
    deps = [":{0}TestsLib"],
)
