#  Copyright (c) 2018 Uber Technologies, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

from __future__ import absolute_import

from .util import seed

uber_poet_header = """
// This code was @generated by Uber Poet, a mock application generator.
// Check it out at https://github.com/uber/uber-poet
"""

swift_func_template = """
public func complexCrap{0}<T>(arg: Int, stuff:T) -> Int {{
    let a = Int(4 * {1} + Int(Float(arg) / 32.0))
    let b = Int(4 * {1} + Int(Float(arg) / 32.0))
    let c = Int(4 * {1} + Int(Float(arg) / 32.0))
    return Int(4 * {1} + Int(Float(arg) / 32.0)) + a + b + c
}}"""

swift_class_template = """
public class MyClass{0} {{
    public let x: Int
    public let y: String

    public init() {{
        x = 7
        y = "hi"
    }}

    {1}
}}"""

objc_header_func_template = """- (int)complexCrap{0}:(int)arg stuff:(nonnull NSString *)stuff;"""

objc_source_func_template = """
- (int)complexCrap{0}:(int)arg stuff:(nonnull NSString *)stuff;
{{
    int a = (int)(4 * self.{1} + (int)((float)arg / 32.0));
    int b = (int)(4 * self.{1} + (int)((float)arg / 32.0));
    int c = (int)(4 * self.{1} + (int)((float)arg / 32.0));
    return (int)(4 * self.{1} + (int)((float)arg / 32.0)) + a + b + c;
}}"""

objc_system_import_template = """
@import Foundation;
"""

objc_header_template = """
@interface MyClass_{0} : NSObject

@property(nonatomic, readonly) int x;
@property(nonatomic, readonly, nonnull) NSString *y;

- (nonnull instancetype)initWithX:(int)x y:(nonnull NSString *)y;
{1}

@end
"""

objc_source_template = """
@implementation MyClass_{0}

- (nonnull instancetype)initWithX:(int)x y:(nonnull NSString *)y;
{{
    self = [super init];
    NSParameterAssert(self);

    _x = x;
    _y = y;

    return self;
}}
{1}

@end
"""


class Language(object):
    SWIFT = 'Swift'
    OBJC = 'Objective-C'

    @staticmethod
    def enum_list():
        return [Language.SWIFT, Language.OBJC]


class FileResult(object):

    def __init__(self, text, functions, classes):
        super(FileResult, self).__init__()
        self.text = text  # string
        self.text_line_count = len(text.split('\n'))
        self.functions = functions  # list of indexes
        self.classes = classes  # {class index: function indexes}


class FileGenerator(object):

    def gen_file(self, class_count, function_count):
        return FileResult("", [], {})


class ObjCHeaderFileGenerator(FileGenerator):

    @staticmethod
    def language():
        return Language.OBJC

    @staticmethod
    def extension():
        return '.h'

    @staticmethod
    def gen_func(nums):
        out = []

        for num in nums:
            out.append(objc_header_func_template.format(num))

        return "\n".join(out), nums

    def get_header(self, objc_class):
        out = []
        class_nums = {}

        for c in objc_class.classes:
            num = c
            func_out, func_nums = self.gen_func(objc_class.classes[c])
            out.append(objc_header_template.format(num, func_out))
            class_nums[num] = func_nums

        return "\n".join(out), class_nums

    def gen_file(self, objc_class):
        class_out, class_nums = self.get_header(objc_class)

        chunks = [uber_poet_header, objc_system_import_template, class_out]

        return FileResult("\n".join(chunks), [], class_nums)


class ObjCSourceFileGenerator(FileGenerator):

    @staticmethod
    def language():
        return Language.OBJC

    @staticmethod
    def extension():
        return '.m'

    @staticmethod
    def gen_func(function_count, var_name):
        out = []
        nums = []

        for _ in xrange(function_count):
            num = seed()
            text = objc_source_func_template.format(num, var_name)
            nums.append(num)
            out.append(text)

        return "\n".join(out), nums

    def gen_class(self, class_count, func_per_class_count):
        out = []
        class_nums = {}

        for _ in xrange(class_count):
            num = seed()
            func_out, func_nums = self.gen_func(func_per_class_count, "x")
            out.append(objc_source_template.format(num, func_out))
            class_nums[num] = func_nums

        return "\n".join(out), class_nums

    def gen_file(self, class_count, function_count, import_list=None):
        if import_list is None:
            import_list = []
        imports = "\n".join(['#import \"{}\"'.format(i) for i in import_list])
        class_out, class_nums = self.gen_class(class_count, 5)

        chunks = [uber_poet_header, objc_system_import_template, imports, class_out]

        return FileResult("\n".join(chunks), [], class_nums)


class SwiftFileGenerator(FileGenerator):

    def __init__(self):
        self.gen_state = {}

    @staticmethod
    def language():
        return Language.SWIFT

    @staticmethod
    def extension():
        return '.swift'

    @staticmethod
    def gen_func(function_count, var_name, indent=0):
        out = []
        nums = []

        for _ in xrange(function_count):
            num = seed()
            text = swift_func_template.format(num, var_name)
            indented_text = '\n'.join(" " * indent + line for line in text.splitlines())
            nums.append(num)
            out.append(indented_text)

        return "\n".join(out), nums

    def gen_class(self, class_count, func_per_class_count):
        out = []
        class_nums = {}

        for _ in xrange(class_count):
            num = seed()
            func_out, func_nums = self.gen_func(func_per_class_count, "x", indent=4)
            out.append(swift_class_template.format(num, func_out))
            class_nums[num] = func_nums

        return "\n".join(out), class_nums

    def gen_file(self, class_count, function_count, import_list=None):
        if import_list is None:
            import_list = []
        imports = "\n".join(["import " + i for i in import_list])
        func_out, func_nums = self.gen_func(function_count, "7")
        class_out, class_nums = self.gen_class(class_count, 5)

        chunks = [uber_poet_header, imports, func_out, class_out]

        return FileResult("\n".join(chunks), func_nums, class_nums)

    @staticmethod
    def gen_main(importing_module_name, class_num, func_num, language):
        import_line = 'import {}'.format(importing_module_name)
        if language == Language.SWIFT:
            action_expr = 'MyClass{}().complexCrap{}(arg: 4, stuff: 2)'.format(class_num, func_num)
        elif language == Language.OBJC:
            action_expr = 'MyClass_{}().complexCrap{}(4, stuff: "2")'.format(class_num, func_num)
        print_line = 'print("\\({})")'.format(action_expr)
        return '\n'.join([uber_poet_header, import_line, print_line])
